QT.Baloo.VERSION = 5.92.0
QT.Baloo.MAJOR_VERSION = 5
QT.Baloo.MINOR_VERSION = 92
QT.Baloo.PATCH_VERSION = 0
QT.Baloo.name = KF5Baloo
QT.Baloo.module = KF5Baloo
QT.Baloo.defines = 
QT.Baloo.includes =  $$PWD/../../../../../include/KF5/Baloo
QT.Baloo.private_includes =
QT.Baloo.libs = $$PWD/../../../../../lib/x86_64-linux-gnu
QT.Baloo.depends = core KCoreAddons KFileMetaData
QT.Baloo.module_config = 
